In [1]:
#Q1 Arrays
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    a=numpy.array(arr[::-1],float)
    return a
    
        
        

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [2]:
#Q2 Shape and Reshape
import numpy
a=numpy.array(input().split(),int)
print(numpy.reshape(a,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#Q3 Transpose and Flatten
import numpy as np



n,m=map(int,input().split())



a=np.array([input().split() for _ in range(n)],int)
    
print(np.transpose(a))
print(a.flatten())


2 2
1 2 
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [12]:
#Q4 Concatenate
import numpy as np

n,m,p=map(int,input().split())

A=np.array([input().split() for _ in range(n)],int)
B=np.array([input().split() for _ in range(m)],int)

con=np.concatenate((A,B),axis=0)
print(con)

4 3 2
1 2
1 2
1 2
1 2
3 4 
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [13]:
#Q5 Zeros and Ones
import numpy as np



m=list(map(int,input().split()))

zero=np.zeros((m),int)
one=np.ones((m),int)
print(zero)
print(one)

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [17]:
#Q6 Eye and Identity
import numpy as np



np.set_printoptions(sign=' ')
a=map(int, input().split())
print(np.eye(*a))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [18]:
#Q7 Array Mathematics
import numpy as np

m,n=list(map(int, input().split()))
b = np.array([input().split() for _ in range(m)], int)
c = np.array([input().split() for _ in range(m)], int)

print(np.add(b,c))
print(np.subtract(b,c))
print(np.multiply(b,c))
print(np.floor_divide(b,c))
print(np.mod(b,c))
print(np.power(b,c))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [19]:
#Q8 Floor, Ceil and Rint
import numpy as np



a=list(map(float,input().split()))

print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [20]:
#Q9 Sum and Prod
import numpy as np

m,n=map(int,input().split())

a=np.array([input().split() for _ in range(m)],int)


sum_arr=np.sum(a,axis=0)
prod_arr=np.prod(sum_arr,axis=0)
print(prod_arr)


2 2
1 2
3 4
24


In [21]:
#Q10 Min and Max
import numpy as np

m,n=map(int,input().split())

a=np.array([input().split() for _ in range(m)],int)

min_a=np.min(a,axis=1)

print(np.max(min_a))
 

4 2
2 5
3 7
1 3
4 0
3


In [22]:
#Q11 Mean, Var, and Std

import numpy as np




m,n=map(int,input().split())

a=np.array([input().split() for _ in range(m)],int)

mean_a=np.mean(a,axis=1)
print(mean_a)

var_a=np.var(a,axis=0)
print(var_a)

np.set_printoptions(legacy='1.13')
print(np.std(a,axis = None))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [23]:
#Q12 Dot and Cross
import numpy as np



m=int(input())

a=np.array([input().split() for _ in range(m)],int)
b=np.array([input().split() for _ in range(m)],int)

print(np.dot(a,b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [25]:
#Q13 Inner and Outer
import numpy as np


a=np.array(input().split() ,int)
b=np.array(input().split(),int)


print(np.inner(a,b))
print(np.outer(a,b))


0 1
2 3
3
[[0 0]
 [2 3]]


In [26]:
#Q14 Polynomials
import numpy as np

a=list(map(float, input().split()))

print(np.polyval(a,float(input())))

1.1 2 3
0
3.0


In [27]:
#Q15 Linear Algebra
import numpy as np
np.set_printoptions(legacy='1.13')


a=int(input())

b=np.array([input().split() for _ in range(a)], float)


    
print(round(np.linalg.det(b),2))

2
1.1 1.1
1.1 1.1
0.0
